In [12]:
import numpy as np
L = [1,2,3]

In [36]:
# Numpy sees everything like a vector - array like a vector; no need of loops for mathematical operations like in lists

In [2]:
A = np.array([1,2,3])

In [7]:
for e in L:
    print(e)
    

1
2
3


In [8]:
for e in A:
    print(e)

1
2
3


In [13]:
L.append(4)
L

[1, 2, 3, 4]

In [14]:
L = L+[5]

In [15]:
L

[1, 2, 3, 4, 5]

In [10]:
#A.append(4) - no such method

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [16]:
# A = A+[5] does not work either

In [17]:
L2 = [] # empty list 
for e in L:
    L2.append(e+e)

In [18]:
L2 

[2, 4, 6, 8, 10]

In [19]:
A+A 

array([2, 4, 6])

In [20]:
# + with list concatenation

In [21]:
# + with numpy array - vector addition - like a matrix

In [22]:
2*A
A

array([1, 2, 3])

In [23]:
2*A

array([2, 4, 6])

In [24]:
2*L 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [25]:
L

[1, 2, 3, 4, 5]

In [26]:
# element wise square

In [31]:
# L ** 2 - error does not work this way
L3=[]
for e in L:
    L3.append(e**2)
L3

[1, 4, 9, 16, 25]

In [32]:
A**2

array([1, 4, 9])

In [33]:
np.sqrt(A**2)

array([1., 2., 3.])

In [34]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [35]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [37]:
# DOT PRODUCTS - MULTIPLICATION ON VECTORS

In [38]:
# a.b = A1B1+A2B2+A3B3 +...+ADBD

In [39]:
a = np.array([1,2])

In [40]:
b = np.array([2,1])

In [41]:
# dot product

In [48]:
dot_prod = 0

In [49]:
for e,f in zip(a,b):
    dot_prod+=e*f

In [50]:
print(dot_prod)

4


In [51]:
a*b

array([2, 2])

In [52]:
np.sum(a*b) 


4

In [54]:
(a*b).sum()

4

In [55]:
np.dot(a,b)

4

In [56]:
c = np.array([3,3])

In [58]:
np.dot(b,c)

9

In [59]:
a.dot(b)

4

In [60]:
b.dot(c) 


9

In [61]:
amag = np.sqrt((a*a).sum()) # magnitude is sqrt(sum(square of all elements of vector))

In [62]:
amag

2.23606797749979

In [63]:
amag = np.linalg.norm(a)

In [64]:
amag

2.23606797749979

In [65]:
cosangle = a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))

In [66]:
cosangle

0.7999999999999998

In [67]:
angle = np.arccos(cosangle)

In [68]:
angle

0.6435011087932847